#!/bin/bash

ORIGINAL=$1

echo "pictures:"
for f in $ORIGINAL/*.jpg
do
    f=$(basename $f)
    cat <<EOF
- filename: $f
  original: wedding-1200/$f
  sizes:
    - wedding-1200/$f
    - wedding-800/$f
    - wedding-480/$f
  thumbnail: wedding-thumbnails/$f
EOF

done
